name: Deploy Frontend

on:
  push:
    branches:
      - dev

jobs:

  build:
    name: Build & Push Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:dev .

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:dev


  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/beauty_3_0
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Pull DOAR frontend
            docker-compose pull frontend

            # Recreate frontend fără să atingem backend/db
            docker-compose up -d --force-recreate --remove-orphans frontend
